-- database schema 
CREATE TABLE IF NOT EXISTS Users (
    UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(128) NOT NULL UNIQUE,
    PassHash VARCHAR(255) NOT NULL,
    UserName VARCHAR(255) UNIQUE,
    FullName VARCHAR(255)
); 